"""Fetch Xiaohongshu (XHS) note comments via Playwright + real page signature.

Why this approach:
- XHS comment API (`/api/sns/web/v2/comment/page`) requires x-s/x-t/x-s-common
  signature headers AND a logged-in cookie (code -101 = "无登录信息").
- The signature is generated by the page's own `window._webmsxyw` function, so we
  load a note page in a real (headless) browser, let the page JS run, then call
  the API from inside the page context with `credentials: 'include'`.
- The note page itself can be loaded from datacenter IPs (no login wall for SSR
  content), but the comment API NEEDS a logged-in cookie -> user must supply it.

Usage:
  python xhs_comments.py <note_url> [note_url ...]
  python xhs_comments.py urls.txt            # one note URL per line

Cookie (required for comments; not needed for images/desc):
  Set env XHS_COOKIE, e.g.:
    XHS_COOKIE="a1=...; web_session=...; ..." python xhs_comments.py <url>
  or pass --cookie-file cookies.txt where each line is "name=value".
  Copy from your logged-in browser: DevTools -> Application -> Cookies ->
  www.xiaohongshu.com -> copy a1 + web_session (or all).

Output: comments/<note_id>.md (nickname | likes | content | time) for each note.
"""
import argparse
import asyncio
import json
import os
import re
import sys
import time

try:
    from playwright.async_api import async_playwright
except ImportError:
    sys.exit("playwright not installed. Run: python -m pip install playwright")

CAPTURE_XS_COMMON_JS = """
(() => {
  try {
    Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
  } catch (e) {}
  const store = (key, value) => {
    if (key && String(key).toLowerCase() === 'x-s-common' && value) {
      window.__xhs_xs_common = value;
    }
  };
  const origSetHeader = XMLHttpRequest.prototype.setRequestHeader;
  XMLHttpRequest.prototype.setRequestHeader = function(key, value) {
    store(key, value);
    return origSetHeader.apply(this, arguments);
  };
  const origFetch = window.fetch;
  window.fetch = function(input, init) {
    try {
      const headers = init && init.headers;
      if (headers) {
        if (typeof Headers !== 'undefined' && headers instanceof Headers) {
          store('x-s-common', headers.get('X-S-Common') || headers.get('x-s-common'));
        } else if (Array.isArray(headers)) {
          for (const [key, value] of headers) store(key, value);
        } else if (typeof headers === 'object') {
          for (const [key, value] of Object.entries(headers)) store(key, value);
        }
      }
    } catch (e) {}
    return origFetch.apply(this, arguments);
  };
  window.__xhs_orig_fetch = origFetch.bind(window);
})();
"""

SIGNED_FETCH_JS = """
async ({ url, method, data }) => {
  if (typeof window._webmsxyw !== 'function') {
    throw new Error('_webmsxyw is not available');
  }
  const parsed = new URL(url);
  const signUrl = parsed.pathname + parsed.search;
  const signed = data == null ? window._webmsxyw(signUrl) : window._webmsxyw(signUrl, data);
  const headers = {
    'content-type': 'application/json;charset=UTF-8',
    'X-s': signed['X-s'] || signed['x-s'] || '',
    'X-t': String(signed['X-t'] || signed['x-t'] || Date.now()),
  };
  if (window.__xhs_xs_common) {
    headers['X-S-Common'] = window.__xhs_xs_common;
  }
  const doFetch = window.__xhs_orig_fetch || fetch;
  const resp = await doFetch(url, {
    method,
    credentials: 'include',
    headers,
    body: data == null ? undefined : JSON.stringify(data),
  });
  const text = await resp.text();
  let body;
  try {
    body = JSON.parse(text);
  } catch (e) {
    body = { success: false, msg: text.slice(0, 300), code: -1 };
  }
  return { status: resp.status, body };
}
"""

NOTE_URL_RE = re.compile(
    r"https?://www\.xiaohongshu\.com/(?:explore|discovery/item)/([0-9a-f]+)"
    r"(?:\?[^#]*xsec_token=([^&]+))?"
)


def parse_note_url(url: str):
    m = NOTE_URL_RE.search(url)
    if not m:
        return None
    return {"note_id": m.group(1), "xsec_token": m.group(2) or ""}


def parse_cookie_from_file(path: str) -> str:
    pairs = []
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        pairs.append(line)
    return "; ".join(pairs)


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("urls", nargs="+", help="note URL(s) or a txt file of URLs")
    ap.add_argument("--cookie-file", help="file with name=value cookie lines")
    ap.add_argument("--out", default="comments", help="output dir (default: comments)")
    args = ap.parse_args()

    # gather urls (expand txt files)
    urls = []
    for u in args.urls:
        if u.lower().endswith(".txt") and os.path.exists(u):
            urls += [l.strip() for l in open(u, encoding="utf-8") if l.strip().startswith("http")]
        else:
            urls.append(u)

    notes = []
    for u in urls:
        n = parse_note_url(u)
        if n:
            notes.append(n)
        else:
            print(f"[skip] cannot parse note URL: {u}")
    if not notes:
        sys.exit("no valid note URLs found")
    print(f"[*] {len(notes)} note(s) to fetch")

    cookie = os.environ.get("XHS_COOKIE", "")
    if args.cookie_file:
        cookie = parse_cookie_from_file(args.cookie_file)
    if not cookie:
        print("[!] no cookie provided. Comments API requires a logged-in cookie.\n"
              "    Set XHS_COOKIE env or pass --cookie-file (see script docstring).")

    os.makedirs(args.out, exist_ok=True)

    pw = await async_playwright().start()
    browser = await pw.chromium.launch(channel="chrome", headless=True)
    context = await browser.new_context(locale="zh-CN", viewport={"width": 1280, "height": 800})
    page = await context.new_page()
    await page.add_init_script(CAPTURE_XS_COMMON_JS)

    if cookie:
        ctx_cookies = []
        for pair in cookie.split(";"):
            pair = pair.strip()
            if "=" not in pair:
                continue
            k, v = pair.split("=", 1)
            ctx_cookies.append({"name": k.strip(), "value": v.strip(),
                                "domain": ".xiaohongshu.com", "path": "/", "secure": True})
        if ctx_cookies:
            await context.add_cookies(ctx_cookies)

    # open first note page to boot the sign runtime
    first = notes[0]
    boot_url = (f"https://www.xiaohongshu.com/explore/{first['note_id']}"
                f"?xsec_token={first['xsec_token']}&xsec_source=pc_search&source=web_explore_feed")
    await page.goto(boot_url, wait_until="domcontentloaded", timeout=45000)
    await page.wait_for_timeout(4000)
    try:
        await page.wait_for_function("() => typeof window._webmsxyw === 'function'", timeout=20000)
    except Exception:
        sys.exit("[!] sign function _webmsxyw did not load (page may be blocked). Aborting.")
    print("[*] sign runtime ready")

    for i, n in enumerate(notes, 1):
        print(f"\n[{i}/{len(notes)}] note {n['note_id']}")
        comments = await fetch_all_comments(page, n)
        if comments is None:
            print(f"  [!!] API error for {n['note_id']} (see message above)")
            continue
        out_path = os.path.join(args.out, f"{n['note_id']}.md")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(f"# Comments for {n['note_id']}\n\n")
            for c in comments:
                f.write(f"- {c}\n")
        print(f"  saved {len(comments)} comments -> {out_path}")

    try:
        await browser.close()
    except Exception:
        pass
    await pw.stop()


async def fetch_all_comments(page, note, max_pages=20):
    """Fetch all comment pages for a note. Returns list of text lines or None on error."""
    base_params = (
        f"note_id={note['note_id']}&xsec_token={note['xsec_token']}"
        f"&top_comment_id=&image_formats=jpg,webp,avif"
        f"&xsec_source=pc_search&source=web_explore_feed"
    )
    cursor = ""
    lines = []
    for p in range(max_pages):
        params = f"{base_params}&cursor={cursor}"
        url = f"https://edith.xiaohongshu.com/api/sns/web/v2/comment/page?{params}"
        result = await page.evaluate(SIGNED_FETCH_JS, {"url": url, "method": "GET", "data": None})
        body = result.get("body") or {}
        code = body.get("code")
        if code != 0:
            msg = body.get("msg") or body.get("message") or ""
            print(f"  API code={code} msg={msg}")
            if code == -101:
                print("  -> comment API requires a LOGGED-IN cookie. Provide XHS_COOKIE from your browser.")
            return None
        data = body.get("data") or {}
        clist = data.get("comments") or []
        for c in clist:
            ui = c.get("user_info") or {}
            nick = ui.get("nickname") or "(anonymous)"
            content = (c.get("content") or "").replace("\n", " ")
            likes = c.get("like_count")
            ct = c.get("create_time")
            lines.append(f"{nick} | +{likes} | {content} | {ct}")
            # sub-comments (楼中楼)
            for sc in c.get("sub_comments") or []:
                sui = sc.get("user_info") or {}
                lines.append(f"  └ {sui.get('nickname') or '(anonymous)'} | +{sc.get('like_count')} | {(sc.get('content') or '').replace(chr(10),' ')}")
        if not data.get("has_more"):
            break
        cursor = data.get("cursor") or ""
        if not cursor:
            break
        await asyncio.sleep(0.5)
    return lines


if __name__ == "__main__":
    asyncio.run(main())
